## Упражнения по библиотеке Numpy

In [1]:
#import sys
#!{sys.executable} -m pip install numpy
#!{sys.executable} -m pip install scipy
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
array = np.random.rand(5, 5)*10
print(array)
array[(array > 3) & (array < 8)] *= -1
print(array)

[[0.18884344 3.43939298 1.23790597 9.91824278 8.70074346]
 [4.92690307 8.23072819 0.5406368  1.98543752 1.57496423]
 [5.6013886  3.16922545 3.72974314 9.93871706 8.16553857]
 [5.78388921 6.44414261 1.77843229 3.8104318  4.03016997]
 [1.772044   6.41533123 5.98857095 3.32866666 0.41126348]]
[[ 0.18884344 -3.43939298  1.23790597  9.91824278  8.70074346]
 [-4.92690307  8.23072819  0.5406368   1.98543752  1.57496423]
 [-5.6013886  -3.16922545 -3.72974314  9.93871706  8.16553857]
 [-5.78388921 -6.44414261  1.77843229 -3.8104318  -4.03016997]
 [ 1.772044   -6.41533123 -5.98857095 -3.32866666  0.41126348]]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
array = np.random.rand(5, 5)
print(array)
array[array == np.max(array)] = 0
print(array)

[[0.82362825 0.8437977  0.34862326 0.05312586 0.50810732]
 [0.78385566 0.98986795 0.09359173 0.51286641 0.1747551 ]
 [0.17737408 0.72174288 0.05844286 0.60655413 0.20648804]
 [0.6439102  0.07308178 0.22064113 0.36209863 0.94299017]
 [0.8042327  0.50743487 0.68106126 0.15935329 0.22214293]]
[[0.82362825 0.8437977  0.34862326 0.05312586 0.50810732]
 [0.78385566 0.         0.09359173 0.51286641 0.1747551 ]
 [0.17737408 0.72174288 0.05844286 0.60655413 0.20648804]
 [0.6439102  0.07308178 0.22064113 0.36209863 0.94299017]
 [0.8042327  0.50743487 0.68106126 0.15935329 0.22214293]]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
def Cartesian(array):
    arr1 = array[0]
    arr2 = array[1]
    cartesian_array = np.array([(i, j) for i in arr1 for j in arr2])

    return cartesian_array
        

array = np.random.rand(2, 5)
print(array)
print()
cartesian_array = Cartesian(array)
print(cartesian_array)

[[0.71073945 0.04137333 0.21800102 0.63478284 0.70258845]
 [0.67563709 0.17909338 0.83790485 0.08919841 0.23955259]]

[[0.71073945 0.67563709]
 [0.71073945 0.17909338]
 [0.71073945 0.83790485]
 [0.71073945 0.08919841]
 [0.71073945 0.23955259]
 [0.04137333 0.67563709]
 [0.04137333 0.17909338]
 [0.04137333 0.83790485]
 [0.04137333 0.08919841]
 [0.04137333 0.23955259]
 [0.21800102 0.67563709]
 [0.21800102 0.17909338]
 [0.21800102 0.83790485]
 [0.21800102 0.08919841]
 [0.21800102 0.23955259]
 [0.63478284 0.67563709]
 [0.63478284 0.17909338]
 [0.63478284 0.83790485]
 [0.63478284 0.08919841]
 [0.63478284 0.23955259]
 [0.70258845 0.67563709]
 [0.70258845 0.17909338]
 [0.70258845 0.83790485]
 [0.70258845 0.08919841]
 [0.70258845 0.23955259]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [24]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

print(A)
print(B)
row_indexes = np.any(np.isin(A, B[0]) & np.isin(A, B[1]), axis=1)
print(A[row_indexes])

[[2 3 1]
 [4 0 2]
 [1 2 4]
 [2 3 1]
 [2 3 4]
 [0 0 2]
 [1 0 0]
 [1 1 3]]
[[0 2]
 [1 2]]
[[2 3 1]
 [4 0 2]
 [1 2 4]
 [2 3 1]
 [2 3 4]
 [0 0 2]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
A = np.random.randint(0, 5, (10, 3))

non_equal_indexes = list(map(lambda x: True if len(np.unique(x)) > 1 else False, A))
print(A[non_equal_indexes])

[[3 0 0]
 [2 2 4]
 [4 3 0]
 [4 0 3]
 [3 2 0]
 [2 3 1]
 [4 3 3]
 [3 3 0]
 [3 2 0]
 [4 4 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [7]:
A = np.random.randint(0, 2, (10, 2))

B = np.unique(A, axis=0)

print(A)
print(B)

[[0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]]
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [8]:
X = np.random.randint(0, 5, (5, 4))
print(X)
# 1 solution
result = 1
for i in range(min(X.shape)):
    if X[i][i] != 0:
        result *= X[i][i]

print(result)
        
# 2 solution
result = np.prod(X.diagonal()[X.diagonal() != 0])
print(result)

[[0 2 2 1]
 [1 3 3 4]
 [0 4 4 2]
 [0 4 2 0]
 [1 0 3 3]]
12
12


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [9]:
X = np.random.randint(0, 5, (4))
Y = np.random.randint(0, 5, (4))
print(X)
print(Y)

# 1 solution
result = True
x = sorted(X.tolist())
y = sorted(Y.tolist())
print(x == y)

# 2 solution
print(np.all(np.sort(X) == np.sort(Y)))

[0 3 3 4]
[4 1 2 4]
False
False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [25]:
X = np.random.randint(0, 5, (10))
print(X)

# 1 solution
max_value = 0
max_index = -1
for i in range(1, len(X)):
    if X[i] > max_value and X[i-1] == 0:
        max_value = X[i]
        max_index = i

print(max_value if max_index > -1 else None)

# 2 solution
def find_max_after_zero(arr):
    non_last_zero_indexes = np.array(np.where(X[:-1] == 0))
    if non_last_zero_indexes.size == 0:
        return None
    indexes_after_zero = non_last_zero_indexes + 1
    max_value = np.max(X[indexes_after_zero])
    return max_value

print(find_max_after_zero(X))

[4 0 0 4 3 2 0 3 3 0]
4
4


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [11]:
X = np.random.randint(0, 5, (6))
print(X)

#1 solution
values = [X[0]]
lengths = [1]
for value in X[1:]:
    if value == values[-1]:
        lengths[-1] += 1
    else:
        values.append(value)
        lengths.append(1)

print(f'values = {values}')
print(f'lengths = {lengths}')

#2 solution
def encode_run_length(arr):
    diffs = np.diff(arr)
    unique_indexes = np.where(diffs != 0)[0] + 1
    unique_indexes = np.insert(unique_indexes, 0, 0)
    
    lengths = np.diff(unique_indexes)
    lengths = np.append(lengths, arr.size - unique_indexes[-1])
    return arr[unique_indexes], lengths

values, lengths = encode_run_length(X)
print(f'values = {values}')
print(f'lengths = {lengths}')

[0 1 0 0 0 0]
values = [0, 1, 0]
lengths = [1, 1, 4]
values = [0 1 0]
lengths = [1 1 4]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [26]:
import time
import scipy
X = np.random.randint(0, 5, (600, 30))
Y = np.random.randint(0, 5, (600, 30))

#1 solution
time1 = time.time()

euclidean_distances = []
def calculate_single_distance(first_sample, second_sample):
    distance = list([x - y for x, y in zip(first_sample, second_sample)])
    squared_distances = list([x**2 for x in distance])
    euclidean_distance = sum(squared_distances)**0.5
    return euclidean_distance

for i in range(X.shape[0]):
    euclidean_distances.append(list())
    for j in range(Y.shape[0]):
        euclidean_distances[i].append(calculate_single_distance(X[i], Y[j]))
    
print(np.array(euclidean_distances))
print()
time2 = time.time()


#2 solution
distance_matrix = np.sum((X[:, None] - Y)**2, axis=2)
euclidean_distances = np.sqrt(distance_matrix)
print(euclidean_distances)
print()
time3 = time.time()

#3 solution
euclidean_distances = scipy.spatial.distance.cdist(X, Y, 'euclidean')
print(euclidean_distances)

time4 = time.time()
print(f'First method time = {time2-time1}')
print(f'Second method time = {time3-time2}')
print(f'Third method time = {time4-time3}')

[[10.86278049 11.40175425 12.4498996  ... 12.72792206 10.34408043
  12.36931688]
 [11.53256259 10.34408043 10.19803903 ... 10.90871211 10.86278049
   9.69535971]
 [10.86278049 11.66190379 10.24695077 ... 11.13552873 10.63014581
  12.52996409]
 ...
 [10.39230485 10.09950494  9.43398113 ... 10.19803903 12.52996409
   9.74679434]
 [10.63014581 10.72380529 12.08304597 ... 10.24695077 12.489996
   9.16515139]
 [ 9.53939201  8.18535277  8.83176087 ... 10.24695077  9.59166305
   9.69535971]]

[[10.86278049 11.40175425 12.4498996  ... 12.72792206 10.34408043
  12.36931688]
 [11.53256259 10.34408043 10.19803903 ... 10.90871211 10.86278049
   9.69535971]
 [10.86278049 11.66190379 10.24695077 ... 11.13552873 10.63014581
  12.52996409]
 ...
 [10.39230485 10.09950494  9.43398113 ... 10.19803903 12.52996409
   9.74679434]
 [10.63014581 10.72380529 12.08304597 ... 10.24695077 12.489996
   9.16515139]
 [ 9.53939201  8.18535277  8.83176087 ... 10.24695077  9.59166305
   9.69535971]]

[[10.86278049 11.4

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [1]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [2]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [3]:
average_calories = np.average(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [4]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [5]:
calorie_median = np.median(calorie_stats)
print(calorie_median)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [8]:
nth_percentile = np.percentile(calorie_stats, 3)
print(nth_percentile)
print('55.6 < 60')
nth_percentile = np.percentile(calorie_stats, 4)
print(nth_percentile)
print('70 > 60')

55.599999999999994
55.6 < 60
70.0
70 > 60


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [19]:
more_calories = calorie_stats[calorie_stats > 60].shape[0] / calorie_stats.shape[0] * 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [20]:
calorie_std = np.std(calorie_stats)
print(calorie_std)
# This std means that the majority of values are in range 85-125 calories and it's more then our value. Unfortunately, 
# std doesn't describe statistics enought to make such decisions. The only what we can say is variation of values is not limited 
# by 100 calories, but for such decision we need another analyze. 

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [21]:
# According to our analyze the most of competitors provide grains with more calories then CrunchieMunchies. The value 
# of CrunchieMunchies grains is lower then 2.41 STD of mean of all competitors or 96% of them. The majority of all 
# competitors provides more then 85 calories in grains. 